name: Clean Changelog

on:
  workflow_call:
    secrets:
      RELEASE_BOT_GITHUB_TOKEN:
        required: true

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.RELEASE_BOT_GITHUB_TOKEN }}

      - name: Configure Git author
        run: |
          git config --global user.name "Open Terms Archive Release Bot"
          git config --global user.email "release-bot@opentermsarchive.org"

      - name: Update changelog for release
        uses: OpenTermsArchive/changelog-action/release@v0.2.0

      - name: Save changelog
        run: |
          git commit -m "Clean changelog" CHANGELOG.md
          git push origin main
