name: Release

on:
  workflow_call:
    inputs:
      publish-npm:
        description: Whether to publish the package to npm
        type: boolean
        default: true
    outputs:
      released:
        description: Whether a release was actually made
        value: ${{ jobs.release.outputs.released }}
      version:
        description: The version that was released
        value: ${{ jobs.release.outputs.version }}
    secrets:
      RELEASE_BOT_GITHUB_TOKEN:
        required: true

permissions:
  id-token: write # Required for npm provenance
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      released: ${{ steps.set-outputs.outputs.released }}
      version: ${{ steps.release-changelog.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.RELEASE_BOT_GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'

      - name: Configure Git author
        run: |
          git config --global user.name "Open Terms Archive Release Bot"
          git config --global user.email "release-bot@opentermsarchive.org"

      - name: Update changelog for release
        id: release-changelog
        uses: OpenTermsArchive/changelog-action/release@v0.2.0

      - name: Bump package version
        run: npm --no-git-tag-version version ${{ steps.release-changelog.outputs.version }}

      - name: Commit CHANGELOG.md and package.json changes and create tag
        run: |
          git add "package.json"
          git add "package-lock.json"
          git add "CHANGELOG.md"
          git commit -m "Release v${{ steps.release-changelog.outputs.version }}"
          git tag v${{ steps.release-changelog.outputs.version }}

      - name: Publish to npm
        if: ${{ inputs.publish-npm }}
        run: npm publish --provenance

      - name: Push changes to repository
        run: git push origin main && git push --tags

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.release-changelog.outputs.version }}
          body: ${{ steps.release-changelog.outputs.content }}
          token: ${{ secrets.RELEASE_BOT_GITHUB_TOKEN }}

      - name: Set outputs
        id: set-outputs
        run: echo "released=true" >> "$GITHUB_OUTPUT"
